# Generated by Django 3.2.19 on 2023-05-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, error_messages={'unique': 'A post with this title already exists. Possible duplicate'}, max_length=255, unique=True),
        ),
    ]
