# Generated by Django 3.2.19 on 2023-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/images/default_profile_xyw4hp', upload_to='images/'),
        ),
    ]
