# Generated by Django 3.2.19 on 2023-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poststatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatus',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Will read', 'Will Read')], max_length=15),
        ),
    ]
