# Generated by Django 3.2.19 on 2023-05-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poststatus', '0002_alter_poststatus_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poststatus',
            unique_together=set(),
        ),
    ]
