# Generated by Django 3.2.19 on 2023-05-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_image'),
        ('poststatus', '0004_poststatus_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatus',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
