# Generated by Django 3.2.19 on 2023-05-20 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfollower',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='postfollower',
            unique_together={('owner', 'post')},
        ),
    ]
