# Generated by Django 3.2.19 on 2023-05-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_followers', '0002_auto_20230520_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfollower',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postfollower',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='posts.post'),
        ),
    ]
